package edu.berkeley.cs.cs162;

public enum ResponseType {
    SHUTTING_DOWN,
    DATABASE_FAILURE,

    USER_ADDED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_NOT_LOGGED_IN,
    USER_ALREADY_LOGGED_IN,

    USER_ADDED_TO_GROUP,
    USER_ADDED_TO_NEW_GROUP,
    USER_REMOVED_FROM_GROUP,

    USER_NOT_FOUND,
    GROUP_NOT_FOUND,
    NAME_CONFLICT,
    INVALID_NAME_OR_PASSWORD,
    USER_ALREADY_MEMBER_OF_GROUP,
    USER_NOT_MEMBER_OF_GROUP,

    MESSAGE_ENQUEUED,
    MESSAGE_BUFFER_FULL,
    SENDER_NOT_FOUND,
    RECEIVER_NOT_FOUND,
    RECEIVER_SAME_AS_SENDER,
    MESSAGE_RECEIVED,
    MESSAGE_DELIVERY_FAILURE,

    DISCONNECT,

    INTERRUPT,
    COMMAND_NOT_FOUND
}
